import { z } from 'zod';
export const offerSchema=z.object({title:z.string().min(3).max(140),venue:z.string().max(100),category:z.enum(['Food & drinks','Fitness','Culture','Outdoors','Events']),neighborhood:z.string().max(80),lat:z.number().min(37.6).max(37.9),lng:z.number().min(-122.6).max(-122.3),description:z.string().max(1200),terms:z.string().min(10).max(1600),source:z.url().refine(v=>v.startsWith('https://')),sourceName:z.string().max(100),schedule:z.string().max(180),eligibility:z.string().max(250),price:z.literal(0),flexible:z.boolean().default(false),duration:z.number().int().min(15).max(240).default(60),bookable:z.boolean().default(true),publicAccess:z.boolean().default(false),trial:z.boolean().default(false),startsAt:z.iso.datetime({offset:true}).optional(),endsAt:z.iso.datetime({offset:true}).optional()});
export function parseJson(text){const clean=text.replace(/^```(?:json)?\s*/,'').replace(/\s*```$/,'').trim();try{return JSON.parse(clean)}catch{const start=clean.indexOf('{'),end=clean.lastIndexOf('}');if(start<0)throw Error('Agent did not return structured results. Its reply is available in the activity feed.');return JSON.parse(clean.slice(start,end+1));}}
export function distance(a,b){const r=Math.PI/180;const dlat=(b.lat-a.lat)*r,dlng=(b.lng-a.lng)*r;const h=Math.sin(dlat/2)**2+Math.cos(a.lat*r)*Math.cos(b.lat*r)*Math.sin(dlng/2)**2;return 6371*2*Math.atan2(Math.sqrt(h),Math.sqrt(1-h));}
export function sfDate(now=new Date()){return new Intl.DateTimeFormat('en-CA',{timeZone:'America/Los_Angeles'}).format(now);}
export function sfInstant(date,time){
 const probe=new Date(`${date}T12:00:00Z`);
 const zone=new Intl.DateTimeFormat('en-US',{timeZone:'America/Los_Angeles',timeZoneName:'shortOffset'}).formatToParts(probe).find(p=>p.type==='timeZoneName').value;
 const offset=Number(zone.replace('GMT',''));
 return new Date(`${date}T${time}:00${offset<0?'-':'+'}${String(Math.abs(offset)).padStart(2,'0')}:00`);
}
export function planDay(offers,{date,interests=[],startHour=10,endHour=20,maxWalkMinutes=35,now=Date.now(),origin={lat:37.789,lng:-122.405}}){
 const start=Math.max(sfInstant(date,`${String(startHour).padStart(2,'0')}:00`).getTime(),Math.ceil(now/900000)*900000),end=sfInstant(date,`${String(endHour).padStart(2,'0')}:00`).getTime();
 let cursor=start,position=origin;const plan=[];let candidates=offers.filter(o=>o.price===0&&!o.trial&&(o.publicAccess===true||o.eligibility==='Everyone')&&(!interests.length||interests.includes(o.category))&&(o.flexible||o.startsAt));
 while(candidates.length&&plan.length<5){
 const ranked=candidates.map(o=>{const walk=Math.ceil(distance(position,o)*1.3/4.5*60);const open=o.openHour==null?start:sfInstant(date,`${String(o.openHour).padStart(2,'0')}:00`).getTime();const close=o.closeHour==null?end:sfInstant(date,`${String(o.closeHour).padStart(2,'0')}:00`).getTime();const earliest=Math.max(cursor+walk*60000,open);const at=o.startsAt?new Date(o.startsAt).getTime():earliest;const finish=o.endsAt?new Date(o.endsAt).getTime():at+o.duration*60000;return{o,walk,at,finish,close,score:walk+(at-earliest)/60000};}).filter(x=>x.walk<=maxWalkMinutes&&x.at>=cursor+x.walk*60000&&x.finish<=x.close&&x.finish<=end&&x.at>=start&&x.finish>x.at).sort((a,b)=>a.score-b.score);
 if(!ranked.length)break;const next=ranked[0];plan.push({offerId:next.o.id,startsAt:new Date(next.at).toISOString(),endsAt:new Date(next.finish).toISOString(),walkMinutes:next.walk,status:'planned'});cursor=next.finish;position=next.o;candidates=candidates.filter(o=>o.id!==next.o.id);
 }return plan;
}
export const escapeIcs=s=>String(s).replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/,/g,'\\,').replace(/;/g,'\\;');
export function makeIcs(plan,offers){const stamp=d=>new Date(d).toISOString().replace(/[-:]/g,'').replace(/\.\d{3}Z/,'Z');return ['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Free SF//Local planner//EN',...plan.flatMap(p=>{const o=offers.find(o=>o.id===p.offerId);return o?['BEGIN:VEVENT',`UID:${p.offerId}-${p.startsAt}@free-sf.local`,`DTSTAMP:${stamp(new Date())}`,`DTSTART:${stamp(p.startsAt)}`,`DTEND:${stamp(p.endsAt)}`,`SUMMARY:${escapeIcs(o.venue+' (planned)')}`,`LOCATION:${escapeIcs(o.venue+', San Francisco')}`,`DESCRIPTION:${escapeIcs('Planned visit; not a confirmed reservation. '+o.terms+' '+o.source)}`,'STATUS:TENTATIVE','END:VEVENT']:[];}),'END:VCALENDAR'].join('\r\n');}
