import React,{useEffect,useState} from 'react';
import {Bot,Copy,KeyRound,ExternalLink,Check} from 'lucide-react';
async function access(method='GET'){const r=await fetch('/api/concierge/bot-access',{method,headers:{'Content-Type':'application/json'},...(method==='POST'?{body:'{}'}:{})});if(!r.ok)throw Error('Could not load bot access.');return r.json()}
export default function BotAccess(){
 const [enabled,setEnabled]=useState(false),[key,setKey]=useState(''),[copied,setCopied]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const base=window.location.origin+'/api/v1';
 useEffect(()=>{access().then(d=>setEnabled(d.enabled)).catch(e=>setError(e.message))},[]);
 async function getKey(){const d=await access('POST');setKey(d.key);setEnabled(true);return d.key}
 async function action(fn){setBusy(true);setError('');try{await fn()}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function copySetup(){const token=key||await getKey();const text=`Use Free SF as my personal San Francisco concierge.\nAPI base URL: ${base}\nAuthorization: Bearer ${token}\nOpenAPI: ${base}/openapi.json\nFirst verify GET /status. Read GET /profile, GET /day-plan and GET /tasks for context. Use PATCH /profile for preferences. Queue each to-do with POST /tasks and JSON {"text":"what I want"}; use a unique Idempotency-Key per task and reuse it on network retries. Poll GET /tasks/{id} every 2-5 seconds. When status is needs_input, read question.prompt and choices, then POST /tasks/{id}/answer with {"answer":"your answer"}; you can answer from your own context without involving the user. Use POST /tasks/{id}/retry for failed or paused work, POST /tasks/{id}/cancel to stop one task, and PATCH /tasks/queue with {"paused":true or false} to pause/resume all work. GET /memory reads notes; PUT /memory/notes writes {"notes":"markdown"} while idle. GET /day-plan returns the schedule and removed IDs; POST /day-plan/{id}/remove or /restore edits it. GET /calendar.ics exports the schedule. Read the OpenAPI specification for remaining capabilities. Internal plan readiness is separate from provider confirmation.\nFor a remote bot, replace the localhost base URL with the HTTPS gateway URL.`;await navigator.clipboard.writeText(text);setCopied('setup')}
 return <section className="bot-access"><span className="bot-icon"><Bot size={22}/></span><h2>Connect your agent.</h2><p>One paste into Instinct, Muse, Grok, or your own bot.</p><button className="button full soft-lime" disabled={busy} onClick={()=>action(copySetup)}>{copied==='setup'?<Check size={14}/>:<Copy size={14}/>} {copied==='setup'?'Copied — paste into your agent':'Copy agent setup'}</button><details className="bot-manual"><summary>Manual setup</summary><label>API address<input aria-label="Bot API address" value={base} readOnly/></label>{key&&<label>API key<div className="bot-key"><input aria-label="Bot API key" type="password" value={key} readOnly/><button aria-label="Copy API key" onClick={()=>action(async()=>{await navigator.clipboard.writeText(key);setCopied('key')})}>{copied==='key'?<Check size={13}/>:<Copy size={13}/>}</button></div></label>}<button className="button outline full" disabled={busy} onClick={()=>action(getKey)}><KeyRound size={13}/>{enabled?'Show API key':'Create API key'}</button><a href="/api/v1/openapi.json" target="_blank" rel="noreferrer">OpenAPI specification<ExternalLink size={12}/></a></details><small>Cloud agent? Use an HTTPS gateway for this API.</small>{error&&<p role="alert">{error}</p>}</section>
}
