import React,{useEffect,useState} from 'react';
import {Bot,Copy,KeyRound,ExternalLink,Check} from 'lucide-react';
async function access(method='GET'){const r=await fetch('/api/concierge/bot-access',{method,headers:{'Content-Type':'application/json'},...(method==='POST'?{body:'{}'}:{})});if(!r.ok)throw Error('Could not load bot access.');return r.json()}
export default function BotAccess(){
 const [enabled,setEnabled]=useState(false),[key,setKey]=useState(''),[copied,setCopied]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const [base,setBase]=useState(window.location.origin+'/api/v1');
 async function endpoint(){try{const d=await(await fetch('/agent-endpoint.json',{cache:'no-store'})).json();if(d.expiresAt>Date.now()&&/^https:\/\/[a-z0-9-]+\.trycloudflare\.com\/api\/v1$/.test(d.baseUrl)){setBase(d.baseUrl);return d.baseUrl}}catch{}return window.location.origin+'/api/v1'}
 useEffect(()=>{endpoint();access().then(d=>setEnabled(d.enabled)).catch(e=>setError(e.message))},[]);
 async function getKey(){const d=await access('POST');setKey(d.key);setEnabled(true);return d.key}
 async function action(fn){setBusy(true);setError('');try{await fn()}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function copySetup(){const base=await endpoint();const token=key||await getKey();const text=`Use Free SF as my personal San Francisco concierge.\nAPI base URL: ${base}\nAuthorization: Bearer ${token}\nRead ${base}/agent.md for the workflow and ${base}/openapi.json for tool schemas. First verify GET /status, then read /profile, /tasks and /sources. You can create tasks, answer clarifications from my context, schedule repeats, update preferences and notes, and manage my itinerary entirely over this API. Use a unique Idempotency-Key for each task and reuse it for retries. Poll task status; inspect result, opportunities and coverage. Do not interpret task completion as a provider reservation. Keep the key in your secret store.${base.startsWith('https:')?'':'\nFor a remote bot, start npm run expose:api and copy this setup again.'}`;await navigator.clipboard.writeText(text);setCopied('setup')}
 return <section className="bot-access"><span className="bot-icon"><Bot size={22}/></span><h2>Connect your agent.</h2><p>One paste into Instinct, Muse, Grok, or your own bot.</p><button className="button full soft-lime" disabled={busy} onClick={()=>action(copySetup)}>{copied==='setup'?<Check size={14}/>:<Copy size={14}/>} {copied==='setup'?'Copied — paste into your agent':'Copy agent setup'}</button><details className="bot-manual"><summary>Manual setup</summary><label>API address<input aria-label="Bot API address" value={base} readOnly/></label>{key&&<label>API key<div className="bot-key"><input aria-label="Bot API key" type="password" value={key} readOnly/><button aria-label="Copy API key" onClick={()=>action(async()=>{await navigator.clipboard.writeText(key);setCopied('key')})}>{copied==='key'?<Check size={13}/>:<Copy size={13}/>}</button></div></label>}<button className="button outline full" disabled={busy} onClick={()=>action(getKey)}><KeyRound size={13}/>{enabled?'Show API key':'Create API key'}</button><a href="/api/v1/openapi.json" target="_blank" rel="noreferrer">OpenAPI specification<ExternalLink size={12}/></a></details><small>{base.startsWith('https:')?'Public API · Keep this computer online.':'Run npm run expose:api for a public HTTPS address.'}</small>{error&&<p role="alert">{error}</p>}</section>
}
