import React,{useState,useEffect} from 'react';
import {CalendarDays,ChevronLeft,ChevronRight,Download,ExternalLink,MapPin,Clock,X,Link2,Utensils,Dumbbell,BookOpen,Ticket,ShowerHead,ArrowUpRight,Trash2} from 'lucide-react';
import BenefitContext from './BenefitContext';
import {googleCalendarLink,sfDay} from './calendar-links';
import './calendar.css';
const noon=date=>new Date(date+'T12:00:00Z');
const addDays=(date,n)=>{const d=noon(date);d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10)};
const time=value=>new Date(value).toLocaleTimeString('en-US',{timeZone:'America/Los_Angeles',hour:'numeric',minute:'2-digit'});
const icons={food:Utensils,fitness:Dumbbell,workspace:BookOpen,event:Ticket};
const label={food:'Meals',fitness:'Move & refresh',workspace:'Recharge',event:'Go out'};
export default function CalendarPage({plan,onConnect,onRemove,initialItem=null,navigation}){
 const today=sfDay(Date.now());
 const [anchor,setAnchor]=useState(today),[day,setDay]=useState(initialItem?sfDay(initialItem.offer.startsAt):addDays(today,1)),[selected,setSelected]=useState(initialItem),[connected,setConnected]=useState(false);
 const items=plan?.items||[],days=Array.from({length:7},(_,i)=>addDays(anchor,i)),dayItems=items.filter(j=>sfDay(j.offer.startsAt)===day);
 useEffect(()=>{let mounted=true;const refresh=()=>fetch('/api/connections').then(r=>r.json()).then(d=>{if(mounted)setConnected((d.connections||[]).some(c=>c.toolkitSlug==='googlecalendar'&&c.status==='ACTIVE'))}).catch(()=>{});refresh();window.addEventListener('focus',refresh);return()=>{mounted=false;window.removeEventListener('focus',refresh)}},[]);
 function shift(n){setAnchor(addDays(anchor,n));setDay(addDays(day,n))}
 return <section className="calendar-page"><div className="calendar-heading"><div><h1>Calendar</h1><p>{plan?.summary.meals||0} meals · {plan?.summary.workouts||0} workouts · {plan?.summary.events||0} things to do</p></div>{navigation}<div className="calendar-actions"><a className="button outline" href="/api/concierge/calendar.ics" download="free-sf-week.ics"><Download size={14}/>Export week</a>{connected?<a className="button dark" href="https://calendar.google.com/calendar/u/0/r" target="_blank" rel="noreferrer"><CalendarDays size={15}/>Google Calendar<ExternalLink size={13}/></a>:<button className="button dark" onClick={onConnect}><Link2 size={14}/>Connect calendar</button>}</div></div>
 <div className="calendar-toolbar"><h2>{noon(anchor).toLocaleDateString('en-US',{month:'long',year:'numeric',timeZone:'UTC'})}</h2><div><button onClick={()=>{setAnchor(today);setDay(today)}}>Today</button><button aria-label="Previous week" onClick={()=>shift(-7)}><ChevronLeft size={17}/></button><button aria-label="Next week" onClick={()=>shift(7)}><ChevronRight size={17}/></button></div></div>
 <div className="calendar-scroll"><div className="calendar-grid">{days.map(date=>{const entries=items.filter(j=>sfDay(j.offer.startsAt)===date);return <div key={date} className={'calendar-day '+(date===day?'is-selected':'')}><button className="calendar-day-label" aria-label={'View '+date} aria-pressed={date===day} onClick={()=>setDay(date)}><span>{date===today?'Today':noon(date).toLocaleDateString('en-US',{weekday:'short',timeZone:'UTC'})}</span><strong>{noon(date).getUTCDate()}</strong><small>{entries.length} stops</small></button><div className="calendar-day-events">{entries.map(j=>{const Icon=icons[j.purpose]||Ticket;return <button className={'calendar-event purpose-'+j.purpose} key={j.id} onClick={()=>{setDay(date);setSelected(j)}}><span><Icon size={13}/>{time(j.offer.startsAt)}</span><strong>{j.offer.title}</strong><small>{j.offer.venue.split(' · ')[0]}</small><b>{j.access} <em>$0</em></b></button>})}{!entries.length&&<p className="calendar-open">{date<today?'Past day':'Open day'}</p>}</div></div>})}</div></div>
 <div className="calendar-foot"><div>{Object.entries(label).map(([k,v])=><span key={k}><i className={'purpose-'+k}/>{v}</span>)}</div><small>Pacific time · Time between stops included</small></div>
 <section className="day-itinerary"><div className="day-heading"><div><h2>{noon(day).toLocaleDateString('en-US',{weekday:'long',month:'short',day:'numeric',timeZone:'UTC'})}</h2></div><span className="day-total">$0<span>planned spend</span></span></div>
 {dayItems.map((j,i)=>{const Icon=icons[j.purpose]||Ticket;return <React.Fragment key={j.id}>{i>0&&<div className="day-gap">{Math.round((new Date(j.offer.startsAt)-new Date(dayItems[i-1].offer.endsAt))/60000)} min between stops</div>}<button className="day-stop" onClick={()=>setSelected(j)}><span className="day-time">{time(j.offer.startsAt)}<small>{time(j.offer.endsAt)}</small></span><span className={'day-icon purpose-'+j.purpose}><Icon size={21}/></span><span className="day-description"><strong>{j.offer.title}</strong><small>{j.offer.benefitSummary}</small><span><MapPin size={12}/>{j.offer.venue}</span></span><span className="day-access">{j.access}<ArrowUpRight size={16}/></span></button></React.Fragment>})}
 {!dayItems.length&&<p className="calendar-open">No scheduled stops here yet.</p>}
 </section>
 {!!plan?.alternatives?.length&&<details className="calendar-alternatives"><summary>{plan.alternatives.length} more events saved</summary>{plan.alternatives.map(j=><a key={j.id} href={j.offer.url} target="_blank" rel="noreferrer">{j.offer.title}<ExternalLink size={12}/></a>)}</details>}
 {selected&&<div className="concierge-overlay" onClick={e=>e.target===e.currentTarget&&setSelected(null)}><div className="week-detail"><button className="setup-close icon-button" aria-label="Close calendar event" onClick={()=>setSelected(null)}><X size={20}/></button><span className="eyebrow muted">{selected.access.toUpperCase()} · $0</span><h2>{selected.offer.title}</h2><BenefitContext offer={selected.offer} details/><p><Clock size={14}/>{time(selected.offer.startsAt)}–{time(selected.offer.endsAt)} · {sfDay(selected.offer.startsAt)}</p><p><MapPin size={14}/>{selected.offer.venue}</p><a className="button dark full" href={googleCalendarLink(selected.offer)} target="_blank" rel="noreferrer"><CalendarDays size={15}/>Add to Google Calendar<ExternalLink size={13}/></a><details className="calendar-evidence"><summary>Visit details & sources</summary><p>{selected.offer.schedule}</p><p>{selected.offer.terms}</p>{[selected.offer.url,...(selected.offer.sources||[])].map(url=><a key={url} href={url} target="_blank" rel="noreferrer">{new URL(url).hostname}<ExternalLink size={12}/></a>)}</details><button className="calendar-remove" onClick={async()=>{await onRemove(selected.id);setSelected(null)}}><Trash2 size={13}/>Remove this stop</button></div></div>}
 </section>
}
