import React,{useState,useEffect,useRef,useCallback} from 'react';
import RFB from '@novnc/novnc';
import {Sparkles,ArrowUpRight,ArrowRight,MapPin,Settings2,Play,Pause,Monitor,Check,CheckCircle2,Clock,CreditCard,ShieldCheck,RefreshCw,X,Plus,CalendarDays,Utensils,Dumbbell,Ticket,Mail,ChevronDown,MousePointer2,LoaderCircle,ExternalLink,Receipt,Globe,Sun,Package,Link2} from 'lucide-react';
import './concierge.css';
import DemoLife from './DemoLife';
import ProfilePage from './ProfilePage';
import CalendarPage from './CalendarPage';
async function api(path,body){const r=await fetch('/api'+path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const d=await r.json();if(!r.ok)throw Error(d.error||'Request failed.');return d;}
function Mascot({large=false}){return <div className={'muse '+(large?'big':'')}><span/><span/><span/><span/><b>••</b></div>}
const categoryIcon={Fitness:Dumbbell,'Meal delivery':Utensils,'Events & food':Ticket};
function Desktop({takeover,onError,onControl}){const screen=useRef(null),rfb=useRef(null);const [status,setStatus]=useState('Connecting to your Agent37 computer…'),[generation,setGeneration]=useState(0);
 useEffect(()=>{let cancelled=false;api('/concierge/computer',{takeover}).then(({ws})=>{if(cancelled)return;const c=new RFB(screen.current,ws);rfb.current=c;c.scaleViewport=true;c.resizeSession=false;c.viewOnly=!takeover;c.background='#edf0e7';c.addEventListener('connect',()=>setStatus('connected'));c.addEventListener('disconnect',()=>setStatus('Connection closed. Reconnect to your computer.'));c.addEventListener('securityfailure',()=>setStatus('Computer connection could not be authenticated.'));}).catch(e=>{setStatus(e.message);onError(e.message)});return()=>{cancelled=true;rfb.current?.disconnect();rfb.current=null}},[generation]);
 useEffect(()=>{if(rfb.current){rfb.current.viewOnly=!takeover;if(takeover)rfb.current.focus()}},[takeover]);
 return <div className="vm-screen-shell"><div ref={screen} className="vm-screen"/>{status!=='connected'&&<div className="vm-connecting"><Monitor size={30}/><p>{status}</p><button onClick={()=>setGeneration(n=>n+1)}><RefreshCw size={14}/>Reconnect</button></div>}<div className="vm-controlbar"><span><span className="live-dot"/>{takeover?'You have control':'Live from the Agent37 VM'}</span><button onClick={onControl}>{takeover?<Play size={13}/>:<MousePointer2 size={13}/>} {takeover?'Return control':'Take control'}</button></div></div>}
export default function Concierge(){
 const [data,setData]=useState(null),[panel,setPanel]=useState(null),[profile,setProfile]=useState(null),[tab,setTab]=useState('life'),[toast,setToast]=useState(null),[busy,setBusy]=useState(false),[showVM,setShowVM]=useState(false),[takeover,setTakeover]=useState(false),[receipt,setReceipt]=useState(null),[connections,setConnections]=useState([]),[authUrl,setAuthUrl]=useState(null),[handoffService,setHandoffService]=useState(null);
 const notify=useCallback(t=>{setToast(t);setTimeout(()=>setToast(null),7000)},[]);
 const refresh=useCallback(async()=>{try{setData(await api('/concierge'))}catch(e){notify(e.message)}},[notify]);
 useEffect(()=>{refresh();const timer=setInterval(refresh,2000);return()=>clearInterval(timer)},[refresh]);
 useEffect(()=>{if(data&&!profile)setProfile(data.profile)},[data]);
 const act=async(fn)=>{setBusy(true);try{await fn();await refresh()}catch(e){notify(e.message)}finally{setBusy(false)}};
 const start=(serviceId,resume=false)=>act(async()=>{if(!data.onboarded){setTab('profile');return;}setTakeover(false);await api(data.demoMode&&!serviceId?'/concierge/demo':'/concierge/start',{serviceId,resume});setShowVM(true);notify('Your agent is taking it from here.');});
 const control=()=>act(async()=>{if(!takeover){setHandoffService(data.mission?.current||null);await api('/concierge/pause',{});}setTakeover(!takeover)});
 const connect=(toolkit)=>act(async()=>{const d=await api('/connect',{toolkit});setAuthUrl(d.redirectUrl);window.open(d.redirectUrl,'_blank','noopener,noreferrer')});
 if(!data)return <div className="loading"><Mascot large/><h2>Getting your life together…</h2></div>;
 const secured=data.results.filter(r=>r.status==='secured'),attention=data.results.filter(r=>r.status==='needs_you'),trials=secured.filter(r=>r.renewalDate||r.renewalAmount),current=data.services.find(s=>s.id===data.mission?.current);
 const totalSpent=secured.reduce((n,r)=>n+(r.totalToday||0),0);
 const nav=[['life','Your free life'],['calendar','Calendar'],['profile','Your profile'],['activity','Agent activity'],['subscriptions','Subscriptions']];
 const edit=()=>{setTab('profile');setShowVM(false)};
 return <div className={"concierge-app "+(data.demoMode?"experience-mode":"")}>
 <header className="concierge-header"><button className="concierge-brand" onClick={()=>setTab('life')}><span className="brand-mark">f<span>↗</span></span>free<span>sf.</span></button><nav className="concierge-nav">{nav.map(([id,label])=><button className={tab===id?'active':''} key={id} onClick={()=>setTab(id)}>{label}{id==='subscriptions'&&trials.length>0&&<i>{trials.length}</i>}</button>)}</nav><div className="concierge-profile"><span className="city-chip"><MapPin size={13}/>San Francisco</span><button onClick={edit} className="user-button"><span>{data.profile.name[0]||'?'}</span>{data.profile.name.split(' ')[0]||'You'}<ChevronDown size={12}/></button></div></header>
 <main className="concierge-main">

 {tab==='calendar'?<CalendarPage bookings={data.bookings||[]} onConnect={()=>{setPanel('connections');api('/connections').then(d=>setConnections(d.connections)).catch(e=>notify(e.message));connect('googlecalendar')}}/>:tab==='profile'?<ProfilePage data={data} onSave={async profile=>{const next=await api('/concierge/profile',profile);setData(next);return next}} onSync={async()=>{const next=await api('/concierge/profile-memory/sync',{});setData(next);return next}} onReadMemory={()=>api('/concierge/profile-memory')}/>:<>
 <section className="agent-hero"><div className="agent-hero-copy"><div className="eyebrow"><span className="live-dot"/>{data.active?'YOUR AGENT IS ON IT':'YOUR AUTONOMOUS LIFE ASSISTANT'}</div><h1>You live your life.<br/><i>I’ll make it free.</i></h1><p>Meals at your door. A workout on the calendar. Plans for tonight.<br/>Your agent finds the offers, fills the forms, and handles the legwork.</p><div className="hero-agent-actions">{data.active?<button className="button dark" onClick={()=>act(()=>api('/concierge/pause',{}))}><Pause size={16}/>Pause agent</button>:<button className="button dark" onClick={()=>start()} disabled={busy}><Sparkles size={17}/>{data.onboarded?'Take care of my week':'Set up my free life'}<ArrowUpRight size={17}/></button>}<button className="text-button" onClick={()=>{setShowVM(!showVM);setTab('life')}}><Monitor size={16}/>{showVM?'Hide computer':'Watch my agent work'}<ArrowUpRight size={14}/></button></div><div className="autonomy-caption"><ShieldCheck size={13}/>It does the work. You step in for secure login, card entry, and consent.</div></div><div className="agent-hero-visual"><div className="muse-ring ring-a"/><div className="muse-ring ring-b"/><div className="muse-ring ring-c"/><div className="hero-muse"><Mascot large/></div><div className="floating-task task-a"><span className="task-symbol"><Utensils size={17}/></span><div>Meals, handled.<small>HelloFresh · Factor</small></div><Sparkles size={13}/></div><div className="floating-task task-b"><span className="task-symbol"><Dumbbell size={17}/></span><div>Move for $0.<small>ClassPass · gym trials</small></div><ArrowUpRight size={15}/></div><div className="floating-task task-c"><span className="task-symbol"><Ticket size={17}/></span><div>Go out. On the house.<small>Luma · local perks</small></div></div><div className="handwritten">your very resourceful<br/><i>plus one.</i></div></div></section>
 <section className="home-strip"><div><span className="home-icon"><MapPin size={18}/></span><span>MAKING LIFE HAPPEN AROUND<strong>{data.profile.address}, {data.profile.city}</strong></span><button onClick={edit} aria-label="Edit address"><Settings2 size={15}/></button></div><div><span>{data.demoMode?'PLANS & PERKS':'SECURED'}</span><strong>{data.demoMode?(data.bookings||[]).filter(j=>j.status==='ready').length:secured.length}<small>{data.demoMode?'handled':'real wins'}</small></strong></div><div><span>{data.demoMode?'YOUR UPFRONT TOTAL':'SPENT TODAY'}</span><strong>{data.demoMode?'$0':'$'+totalSpent.toFixed(2)}</strong></div><div><span>{data.demoMode?'MORE PERKS':'NEEDS YOU'}</span><strong>{data.demoMode?(data.demo?.opportunities||[]).filter(o=>!o.simulated).length:attention.length}<small>{data.demoMode?'meal offers':'quick steps'}</small></strong></div></section>
 {showVM&&<section className="computer-section"><div className="computer-title"><div><span className="live-dot"/><h3>Your agent’s computer</h3><span className="computer-origin">AGENT37 VM</span></div><div><span>{data.demoMode&&data.active?'Researching real offers':current?`Working on ${current.name}`:takeover?'Your secure handoff':'Ready to work'}</span><button className="icon-button" aria-label="Close computer" onClick={()=>{setShowVM(false);setTakeover(false)}}><X size={17}/></button></div></div>{data.computer.desktopReady?<Desktop takeover={takeover} onError={notify} onControl={control}/>:<div className="desktop-building"><Mascot/><h3>Your computer is getting ready.</h3><p>The Agent37 desktop is being installed. This is a real persistent browser, not a demo animation.</p><LoaderCircle size={18} className="spin"/></div>}<div className="computer-foot"><ShieldCheck size={14}/>{data.demoMode?'Live research on the Agent37 computer. Demo confirmations do not submit anything to providers.':takeover?'You control the real merchant page. Enter passwords and card details here; they are not sent to the chat.':'Watch the agent browse and fill forms. Take control when a provider needs your login or card.'}{takeover&&<button onClick={()=>{setTakeover(false);if(handoffService)start(handoffService,true);else notify('Select Resume on the service you just completed.')}}>I’ve finished my step<ArrowRight size={14}/></button>}</div></section>}
 <div className="life-columns"><section className="life-primary">
 {tab==='life'&&data.demoMode&&<DemoLife demo={data.demo} active={data.active} name={data.profile.name} bookings={data.bookings||[]} busy={busy} onResume={()=>act(()=>api('/concierge/bookings/resume',{}))} onManage={(id,action)=>act(async()=>{await api('/concierge/bookings/'+id,{action});notify(action==='remove'?'Removed from your week.':'Restored. Scout can finish planning it.');})}/> }
 {tab==='life'&&!data.demoMode&&<><div className="life-section-heading"><div><div className="eyebrow muted">NOT A TO-DO LIST. A DONE-FOR-YOU LIFE.</div><h2>{secured.length?'Look what your agent got.':'Your agent’s working list.'}</h2></div><span className="tiny-badge">{data.profile.goals.length} services in play</span></div>
 <div className="service-grid">{data.services.filter(s=>data.profile.goals.includes(s.id)).map(s=>{const r=data.results.find(r=>r.serviceId===s.id),working=data.active&&current?.id===s.id,Icon=categoryIcon[s.category]||Globe;return <article className={'service-card '+(working?'is-working':'')+' '+(r?.status==='secured'?'is-secured':'')} key={s.id}><div className="service-card-head"><span className="service-logo" style={{background:s.color}}>{s.mark}</span><div><h3>{s.name}</h3><span><Icon size={10}/>{s.category}</span></div><span className={'service-status '+(r?.status||'queued')}>{working?<><LoaderCircle className="spin" size={11}/>Working</>:r?.status==='secured'?<><Check size={11}/>Secured</>:r?.status==='needs_you'?'Needs you':r?.status==='not_free'?'Cost found':r?.status==='unavailable'?'Unavailable':'On the list'}</span></div><h4>{working?`I’m handling ${s.name}.`:(r?.summary?.startsWith('[\n')?'Recovering the provider response':r?.title)||({classpass:'A new routine, without the bill.',hellofresh:'Dinner should take care of itself.',factor:'Your fridge, a little more full.',luma:'You have better plans tonight.',fitness:'A gym pass with your name on it.'}[s.id])}</h4><p>{working?'Opening the real website, checking the offer, and working through the forms.':(r?.summary?.startsWith('[\n')?'The attempt finished, but a display error needs repair. The original response is retained on the agent’s computer.':r?.summary)||'Your agent will find a real offer, check the terms, and work through signup for you.'}</p>{r&&<div className="result-facts">{r.totalToday!=null&&<span>Due today<strong>${r.totalToday.toFixed(2)}</strong></span>}{r.fieldsFilled?.length>0&&<span>Handled<strong>{r.fieldsFilled.length} form fields</strong></span>}{r.confirmation&&<span>Confirmation<strong>{r.confirmation}</strong></span>}</div>}{r?.nextAction&&<div className="needs-you-line"><span className="attention-dot"/>{r.nextAction}</div>}<div className="service-footer">{working?<button onClick={()=>setShowVM(true)}>Watch it happen<Monitor size={14}/></button>:r?.status==='secured'?<button onClick={()=>setReceipt(r)}>View receipt<Receipt size={14}/></button>:r?.status==='needs_you'?<><button onClick={()=>act(async()=>{await api('/concierge/handoff',{serviceId:s.id});setHandoffService(s.id);setTakeover(true);setShowVM(true);notify(`${s.name} is open in your agent’s browser. Finish your step, then return control.`)})}>Open secure handoff<ArrowUpRight size={14}/></button><button className="resume-service" disabled={data.active} onClick={()=>start(s.id,true)} aria-label={`Resume ${s.name}`}><Play size={13}/></button></>:<button disabled={data.active||busy} onClick={()=>start(s.id)}>{r?'Try another offer':'Let my agent handle it'}<Sparkles size={14}/></button>}{r?.screenshotPath&&<button className="proof-button" aria-label={`View ${s.name} evidence`} onClick={()=>setReceipt(r)}><Receipt size={13}/></button>}</div></article>})}</div>
 </>}
 {tab==='activity'&&<><div className="life-section-heading"><div><div className="eyebrow muted">THE WORK BEHIND YOUR FREE LIFE.</div><h2>Every move, in the open.</h2></div><button className="button outline" disabled={busy||data.active} onClick={()=>act(async()=>{await api('/concierge/sync',{});notify('Synced the latest outcomes from your agent computer.');})}><RefreshCw size={14}/>Sync from VM</button></div><Activity data={data} full/></>}
 {tab==='subscriptions'&&<><div className="life-section-heading"><div><div className="eyebrow muted">ALL THE PERKS. NONE OF THE SURPRISES.</div><h2>Trials with an exit plan.</h2></div><CreditCard size={25}/></div><div className="subscription-intro"><ShieldCheck size={21}/><div><strong>Card-supported trials, handled carefully.</strong><p>Your agent prepares the real checkout, surfaces the renewal terms, and leaves secure card entry to you. Once a trial is confirmed, its renewal and cancellation details appear here.</p></div></div>{data.results.filter(r=>r.renewalDate||r.renewalAmount||r.actionType==='card'||r.category==='Meal delivery').map(r=><div className="subscription-row" key={r.id}><div><strong>{r.provider}</strong><p>{r.title}</p><span>{r.renewalAmount!=null?`Renews at $${r.renewalAmount}`:'Renewal amount not yet confirmed'}{r.renewalDate?` on ${r.renewalDate}`:''}</span>{r.cancelBy&&<b>Cancel before {r.cancelBy}</b>}</div><button className="button outline" onClick={()=>{setShowVM(true);setTakeover(false)}}>Open computer<ArrowUpRight size={14}/></button></div>)}{!data.results.some(r=>r.renewalDate||r.renewalAmount||r.actionType==='card'||r.category==='Meal delivery')&&<div className="subscriptions-empty"><Package size={35}/><h3>Your perks are on their way.</h3><p>Start the agent to check ClassPass, HelloFresh, Factor, and fitness offers. Only actual subscription results show up here.</p><button className="button dark" onClick={()=>start()}>Find my free trials<Sparkles size={16}/></button></div>}</>}
 </section><aside className="life-rail"><div className="agent-live-card"><div className="agent-live-head"><Mascot/><div><strong>Scout</strong><span><i className="live-dot"/>{data.active?'Working for you':'Your agent on standby'}</span></div><span className="cloud-tag">AGENT37</span></div><p className="agent-quote">{data.active?`“You’ve got better things to do. I’m taking care of ${current?.name||'the details'}.”`:data.demoMode&&data.demo?.opportunities?.length?'“You go enjoy the city. I’ve got the legwork.”':'“Tell me where you live and what you love. I’ll handle the rest.”'}</p>{data.demoMode&&!data.active?<div className="scout-complete"><span><CheckCircle2 size={16}/>Your week has some good things in it.</span><p>Your plans and perks stay here. Open any one to manage it, or add your week to your calendar.</p><button onClick={()=>setTab('activity')}>See how Scout did it<ArrowRight size={13}/></button></div>:<Activity data={data}/>}<button className="button full soft-lime" onClick={()=>{setShowVM(true);setTab('life')}}><Monitor size={15}/>See my computer<ArrowUpRight size={15}/></button></div><div className="autopilot-card"><div><Sun size={19}/><strong>A little help, every day.</strong></div><p>Let Scout check for new offers every morning at 8 AM, even when this app is closed.</p><button className={'daily-toggle '+(data.cron?.enabled?'enabled':'')} disabled={busy||data.demoMode} onClick={()=>act(async()=>{await api('/concierge/schedule',{enabled:!data.cron?.enabled});notify(data.cron?.enabled?'Daily autopilot paused.':'Daily autopilot enabled on the Agent37 VM.')} )}><span className="toggle-track"><i/></span>{data.demoMode?'Daily execution available in real mode':data.cron?.enabled?'Daily autopilot on':'Enable daily autopilot'}</button></div><button className="accounts-link" onClick={()=>{setPanel('connections');api('/connections').then(d=>setConnections(d.connections)).catch(e=>notify(e.message))}}><Link2 size={17}/><div>Connect your accounts<small>Calendar, Gmail, and your everyday apps</small></div><ArrowUpRight size={15}/></button></aside></div>
 </>}
 <footer className="concierge-footer"><span>free sf. <i>Very expensive city. Very resourceful agent.</i></span><div><span className="live-dot"/>Agent37 computer <b>×</b> OpenAI <b>×</b> <span className={data.storage.healthy?'db-good':'db-off'}>InsForge {data.storage.healthy?'connected':'needs attention'}</span><span className="local-pill">LOCAL</span></div></footer>
 </main>
 {panel==='connections'&&<div className="concierge-overlay"><div className="connections-modal"><button className="setup-close icon-button" onClick={()=>setPanel(null)} aria-label="Close connections"><X size={20}/></button><div className="eyebrow muted">MAKE IT PERSONAL.</div><h2>A connected life.</h2><p>Give your agent the accounts it needs to handle the details.</p>{[['googlecalendar','Google Calendar',CalendarDays],['gmail','Gmail',Mail]].map(([id,name,Icon])=><div className="account-row" key={id}><Icon size={25}/><div><strong>{name}</strong><span>{connections.some(c=>c.toolkitSlug===id&&c.status==='ACTIVE')?'Connected':'Not connected'}</span></div><button className="button outline" onClick={()=>connect(id)}>Connect<ArrowUpRight size={14}/></button></div>)}{authUrl&&<a href={authUrl} target="_blank" rel="noreferrer" className="source-link">Continue secure authorization<ExternalLink size={14}/></a>}<button className="button outline full" onClick={()=>act(async()=>{setConnections((await api('/connections')).connections)})}><RefreshCw size={14}/>Refresh connections</button><div className="payment-policy"><CreditCard size={20}/><div><strong>ClassPass, Luma, and meal subscriptions</strong><p>Sign in once in your agent’s persistent browser. It keeps the session for the next time you need something handled.</p><button className="text-button" onClick={()=>{setPanel(null);setShowVM(true);setTakeover(true)}}>Open secure browser<ArrowUpRight size={14}/></button></div></div></div></div>}
 {receipt&&<div className="concierge-overlay" onClick={e=>e.target===e.currentTarget&&setReceipt(null)}><div className="receipt-modal"><button className="setup-close icon-button" onClick={()=>setReceipt(null)} aria-label="Close receipt"><X size={20}/></button><span className="eyebrow muted">REAL PROVIDER EVIDENCE</span><h2>{receipt.provider}</h2><p>{receipt.summary}</p>{receipt.confirmation&&<div className="receipt-reference">{receipt.confirmation}</div>}{receipt.receiptText&&<blockquote>{receipt.receiptText}</blockquote>}{receipt.screenshotPath&&<img src={'/api/concierge/receipt/'+receipt.serviceId} alt={`Actual ${receipt.provider} page captured by the agent`}/>}<a className="button outline full" href={receipt.url} target="_blank" rel="noreferrer">Open provider<ExternalLink size={15}/></a></div></div>}
 {toast&&<div className="toast" role="status"><Sparkles size={16}/>{toast}<button aria-label="Dismiss notification" onClick={()=>setToast(null)}><X size={15}/></button></div>}
 </div>
}
function Activity({data,full=false}){const events=full?data.activity:data.activity.slice(0,4);return <div className={'concierge-activity '+(full?'full-activity':'')}>{!events.length?<div className="waiting-activity"><Globe size={18}/><span>Ready for your first mission.</span></div>:events.map(e=><div className={'concierge-event '+e.kind} key={e.id}><span>{e.kind==='secured'?<CheckCircle2 size={14}/>:e.kind==='browser'?<Monitor size={14}/>:e.kind==='attention'?<Clock size={14}/>:<Sparkles size={14}/>}</span><div><small>{e.serviceId?.toUpperCase()||'SCOUT'}<time>{new Date(e.at).toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit'})}</time></small><p>{/^(from hermes_tools|import |python |print\(|browser_console)/.test(e.text)?'Checked source details.':e.kind==='browser'&&/^e\d+$/.test(e.text)?'Advanced through the provider’s signup flow.':e.text==='browser_snapshot'?'Read the current provider page.':e.text==='browser_vision'?'Checked the page visually.':e.text}</p></div></div>)}</div>}
