import React,{useState} from 'react';
import BenefitContext from './BenefitContext';
import {googleCalendarLink} from './calendar-links';
import {ArrowUpRight,Check,Search,Clock,MapPin,Ticket,Dumbbell,X,ChevronRight,CalendarDays,RotateCcw,LoaderCircle,Trash2,Package} from 'lucide-react';
const day=d=>new Date(d).toLocaleDateString('en-US',{timeZone:'America/Los_Angeles',weekday:'short',month:'short',day:'numeric'});
const time=d=>new Date(d).toLocaleTimeString('en-US',{timeZone:'America/Los_Angeles',hour:'numeric',minute:'2-digit'});
export default function DemoLife({demo,active,name,bookings=[],onManage,onResume,busy}){
 const [selectedId,setSelectedId]=useState(null);
 const statusText={queued:'Queued',preparing:'Preparing',booking:'Booking',ready:'Ready',paused:'Paused',cancelled:'Removed'};
 const raw=demo?.opportunities||[],all=[...raw,...bookings.filter(j=>!raw.some(o=>o.url===j.offer.url)).map(j=>j.offer)];
 const items=all.map(o=>({...o,job:bookings.find(j=>j.offer.url===o.url)})),wins=items.filter(o=>o.simulated&&o.job?.status!=='cancelled'),events=wins.filter(o=>o.kind==='event').sort((a,b)=>new Date(a.startsAt)-new Date(b.startsAt)),passes=wins.filter(o=>o.kind!=='event'),review=items.filter(o=>!o.simulated),removed=items.filter(o=>o.job?.status==='cancelled');
 const selected=items.find(o=>o.id===selectedId),setSelected=o=>setSelectedId(o?.id||null),ready=bookings.filter(j=>j.status==='ready').length,pending=wins.some(o=>!o.job||['queued','paused'].includes(o.job.status));

 return <section className="week-life"><div className="week-heading"><div><span className="eyebrow muted">LESS PLANNING. MORE LIVING.</span><h2>{active?'I’m putting your week together.':wins.length?'You’ve got plans.':'Leave the legwork to Scout.'}</h2></div>{wins.length>0&&<span className="week-handled"><Check size={13}/>{ready} things off your plate</span>}</div>
 <div className="mission-controls"><div className={'mission-stage '+(demo?.opportunities?.length?'done':'')}><Search size={14}/><span>Find real offers</span></div><i/><div className={'mission-stage '+(bookings.length?'done':'')}><LoaderCircle size={14} className={active&&demo?.status==='booking'?'spin':''}/><span>Arrange your week</span></div><i/><div className={'mission-stage '+(ready?'done':'')}><Check size={14}/><span>{ready?`${ready} ready`:'Enjoy your city'}</span></div>{!active&&pending&&<button disabled={busy} onClick={onResume}>Finish planning<ChevronRight size={13}/></button>}{ready>0&&<a href="/api/concierge/calendar.ics" download="free-sf-week.ics"><CalendarDays size={14}/>Add to calendar</a>}</div>
 {!items.length&&<div className="week-empty"><Search size={30}/><h3>{active?'A little searching. A lot less work for you.':'Your next good week starts here.'}</h3><p>{active?'Scout is checking real events, trial offers, and the fine print.':'One click above. Your agent finds the perks and puts your week together.'}</p></div>}
 {demo?.error&&<div className="needs-you-line">{demo.error}</div>}
 {events.length>0&&<div className="week-plans">{events.map(o=><button className="week-plan" key={o.id} onClick={()=>setSelected(o)}><div className="week-date"><span>{new Date(o.startsAt).toLocaleDateString('en-US',{timeZone:'America/Los_Angeles',weekday:'short'})}</span><strong>{new Date(o.startsAt).toLocaleDateString('en-US',{timeZone:'America/Los_Angeles',day:'numeric'})}</strong></div><div className="week-plan-copy"><span className="week-category">{o.category} <i/> {time(o.startsAt)}</span><h3>{o.title}</h3><BenefitContext offer={o}/><span className="week-location"><MapPin size={12}/>{o.venue}</span></div><div className="week-plan-end"><strong>$0</strong><span>{o.job?.status==='ready'?'In your week':statusText[o.job?.status]||'Queued'} {o.job?.status==='ready'?<Check size={11}/>:<Clock size={11}/>}</span></div><ChevronRight size={17}/></button>)}</div>}
 {passes.length>0&&<><div className="wallet-heading"><h3>Your little book of perks.</h3><span>FOR {name?.split(' ')[0]?.toUpperCase()||'YOU'}</span></div><div className="perk-wallet">{passes.map((o,i)=><button className={'perk-pass pass-'+i%2} key={o.id} onClick={()=>setSelected(o)}><div className="pass-top"><span><Dumbbell size={17}/>FITNESS PASS</span><ArrowUpRight size={17}/></div><h3>{o.title}</h3><BenefitContext offer={o}/><div className="pass-holder"><span>MADE FOR<strong>{name||'You'}</strong></span><span className="pass-price">$0<small>to get moving</small></span></div><div className="pass-tear"/><div className="pass-bottom"><span>{o.job?.status==='ready'?<Check size={13}/>:<Clock size={13}/>} {o.job?.status==='ready'?'Your pass is ready':statusText[o.job?.status]||'Queued for Scout'}</span><span>View pass<ChevronRight size={13}/></span></div></button>)}</div></>}
 {removed.length>0&&<details className="removed-plans"><summary>{removed.length} removed plan{removed.length===1?'':'s'}</summary>{removed.map(o=><div key={o.id}><span>{o.title}</span><button disabled={busy} onClick={()=>onManage(o.job.id,'restore')}><RotateCcw size={12}/>Restore</button></div>)}</details>}
 {review.map(offer=><div className="week-review" key={offer.id}><span className="review-icon"><Package size={18}/></span><div><strong>{offer.title}</strong><BenefitContext offer={offer}/></div><button onClick={()=>setSelected(offer)}>Details<ArrowUpRight size={13}/></button></div>)}
 {items.length>0&&<div className="week-footnote"><span className="live-dot"/>Found on the live web · {active?'Searching now':new Date(demo.finishedAt||demo.startedAt).toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit'})} · Powered by Agent37</div>}
 {selected&&<div className="concierge-overlay" onClick={e=>e.target===e.currentTarget&&setSelected(null)}><div className="week-detail"><button className="setup-close icon-button" onClick={()=>setSelected(null)} aria-label="Close details"><X size={20}/></button><span className="eyebrow muted">{selected.category}</span><h2>{selected.title}</h2><BenefitContext offer={selected} details/><p><Clock size={15}/>{selected.schedule}</p><p><MapPin size={15}/>{selected.venue}</p><div className="detail-price">{selected.priceToday===null?'Price to confirm':`$${selected.priceToday}`}<small>{selected.priceEvidence}</small></div>{selected.job&&<div className="booking-record"><span>{statusText[selected.job.status]}</span><small>For {selected.job.person.name}</small>{selected.job.history.slice(-3).map((h,i)=><p key={i}><Check size={12}/>{statusText[h.status]} <time>{new Date(h.at).toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit'})}</time></p>)}</div>}{selected.startsAt&&<a className="button outline full" href={googleCalendarLink(selected)} target="_blank" rel="noreferrer"><CalendarDays size={14}/>Add to Google Calendar<ArrowUpRight size={13}/></a>}<h4>The details</h4><p>{selected.terms}</p><p>{selected.eligibility}</p>{selected.renewal&&<p>{selected.renewal}</p>}<a className="button dark full" href={selected.url} target="_blank" rel="noreferrer">View original source<ArrowUpRight size={15}/></a>{selected.job&&selected.job.status!=='cancelled'&&<button className="remove-plan-button" disabled={busy} onClick={async()=>{await onManage(selected.job.id,'remove');setSelected(null)}}><Trash2 size={14}/>Remove from my week</button>}</div></div>}
 </section>
}
