import React,{useEffect,useState} from 'react';
import {Utensils,Dumbbell,Music,Palette,Code2,Trees,GraduationCap,Users,Check,MapPin,UserRound,SlidersHorizontal,NotebookPen,FileText,RefreshCw,ChevronRight,X,LoaderCircle} from 'lucide-react';
import './profile.css';
import BotAccess from './BotAccess';
const interests=[['food','Food & drinks',Utensils],['fitness','Fitness',Dumbbell],['music','Live music',Music],['arts','Arts & culture',Palette],['tech','Tech',Code2],['outdoors','Outdoors',Trees],['learning','Learning',GraduationCap],['social','Meeting people',Users]];
export default function ProfilePage({data,onSave,onSync,onReadMemory}){
 const [draft,setDraft]=useState(data.profile),[saving,setSaving]=useState(false),[message,setMessage]=useState(''),[notebook,setNotebook]=useState(null),[reading,setReading]=useState(false),[file,setFile]=useState('profile');
 const saved=JSON.stringify(data.profile);
 useEffect(()=>{setDraft(data.profile)},[saved]);
 const dirty=JSON.stringify(draft)!==saved,locked=saving||data.active||data.profileSyncing;
 const set=(key,value)=>setDraft(p=>({...p,[key]:value}));
 const toggle=(key,id)=>set(key,draft[key].includes(id)?draft[key].filter(v=>v!==id):[...draft[key],id]);
 async function save(e){e.preventDefault();setSaving(true);setMessage('');try{const next=await onSave(draft);setMessage(next.profileMemory?.status==='synced'?'Saved. Scout is up to date.':'Saved. Computer sync needs a retry.')}catch(e){setMessage(e.message)}finally{setSaving(false)}}
 async function sync(){setSaving(true);setMessage('');try{await onSync();setMessage('Scout is up to date.')}catch(e){setMessage(e.message)}finally{setSaving(false)}}
 async function read(){setReading(true);try{setNotebook(await onReadMemory())}catch(e){setMessage(e.message)}finally{setReading(false)}}
 return <section className="profile-page"><div className="profile-heading"><div><p>Tell Scout what a good week looks like.</p></div><span className="profile-avatar">{draft.name?.[0]||<UserRound size={26}/>}</span></div>
 <div className="profile-layout"><form onSubmit={save} className="profile-form"><fieldset disabled={locked}>
 <section className="profile-card"><h2><SparkleIcon/>What are you into?</h2><div className="interest-grid">{interests.map(([id,label,Icon])=><button type="button" key={id} aria-pressed={draft.interests.includes(id)} className={draft.interests.includes(id)?'selected':''} onClick={()=>toggle('interests',id)}><Icon size={18}/>{label}{draft.interests.includes(id)&&<Check size={13}/>}</button>)}</div></section>
 <section className="profile-card"><h2><SlidersHorizontal size={18}/>Your kind of week</h2><div className="profile-fields"><label>Best time<select value={draft.timePreference} onChange={e=>set('timePreference',e.target.value)}><option value="any">Any time</option><option value="mornings">Mornings</option><option value="afternoons">Afternoons</option><option value="evenings">Evenings</option><option value="weekends">Weekends</option></select></label><label>How far from home?<select value={draft.maxDistanceMiles} onChange={e=>set('maxDistanceMiles',Number(e.target.value))}>{[...new Set([1,3,5,10,25,draft.maxDistanceMiles])].sort((a,b)=>a-b).map(n=><option key={n} value={n}>Within {n} {n===1?'mile':'miles'}</option>)}</select></label><label>Food preferences<select value={draft.diet} onChange={e=>set('diet',e.target.value)}>{['No preference','Vegetarian','Vegan','Pescatarian','High protein','Gluten free'].map(v=><option key={v}>{v}</option>)}</select></label><label>Maximum upfront cost ($)<input type="number" min="0" max="100" value={draft.maxUpfront} onChange={e=>set('maxUpfront',Number(e.target.value))}/></label></div><label className="profile-checkbox"><input type="checkbox" checked={draft.allowTrials} onChange={e=>set('allowTrials',e.target.checked)}/>Include free subscription trials</label><label className="profile-checkbox"><input type="checkbox" checked={draft.communityMeals!==false} onChange={e=>set('communityMeals',e.target.checked)}/>Include community meals</label></section>
 <section className="profile-card"><h2><UserRound size={18}/>Your details</h2><div className="profile-fields"><label>Name<input required autoComplete="name" value={draft.name} onChange={e=>set('name',e.target.value)}/></label><label>Email<input required type="email" autoComplete="email" value={draft.email} onChange={e=>set('email',e.target.value)}/></label><label className="wide">Home address<input required autoComplete="street-address" value={draft.address} onChange={e=>set('address',e.target.value)}/></label><label>City<input required value={draft.city} onChange={e=>set('city',e.target.value)}/></label><label>ZIP code<input autoComplete="postal-code" value={draft.zip} onChange={e=>set('zip',e.target.value)}/></label><label>Phone<input type="tel" autoComplete="tel" value={draft.phone} onChange={e=>set('phone',e.target.value)} placeholder="Optional"/></label></div>
 <details className="profile-advanced"><summary>More signup details</summary><div className="profile-fields"><label>Company<input value={draft.company||''} onChange={e=>set('company',e.target.value)}/></label><label>Job title<input value={draft.jobTitle||''} onChange={e=>set('jobTitle',e.target.value)}/></label><label className="wide">LinkedIn<input value={draft.linkedin||''} onChange={e=>set('linkedin',e.target.value)}/></label><label className="wide">Priority event URL<input type="url" value={draft.eventUrl||''} onChange={e=>set('eventUrl',e.target.value)}/></label><label>State<input value={draft.state} onChange={e=>set('state',e.target.value)}/></label></div></details></section>
 <section className="profile-card"><h2><NotebookPen size={18}/>Anything Scout should know?</h2><textarea aria-label="Instructions for Scout" maxLength="1000" rows="3" value={draft.notes} onChange={e=>set('notes',e.target.value)} placeholder="No early classes. Prefer outdoor events. Already tried ClassPass."/><details className="profile-advanced"><summary>Services to explore</summary><div className="profile-services">{data.services.map(s=><button type="button" key={s.id} aria-pressed={draft.goals.includes(s.id)} className={draft.goals.includes(s.id)?'selected':''} onClick={()=>toggle('goals',s.id)}>{draft.goals.includes(s.id)&&<Check size={12}/>} {s.name}</button>)}</div></details></section>
 </fieldset><div className="profile-save"><span role="status">{message||(data.active?'Pause Scout to edit.':dirty?'Unsaved changes':'Your settings stay with Scout.')}</span><button className="button dark" type="submit" disabled={locked||!draft.goals.length}>{saving?<LoaderCircle size={15} className="spin"/>:<Check size={15}/>} {saving?'Saving…':'Save profile'}</button></div></form>
 <div className="profile-side"><aside className="profile-memory"><div className="memory-icon"><NotebookPen size={29}/></div><span className="eyebrow muted">SCOUT’S NOTEBOOK</span><h2>A little memory.<br/>A better week.</h2><p>Your preferences travel with your agent.</p><div className="memory-file"><FileText size={18}/><div><strong>PROFILE.md</strong><span>Your saved preferences</span></div>{data.profileMemory?.status==='synced'&&<Check size={13}/>}</div><div className="memory-file"><NotebookPen size={18}/><div><strong>NOTES.md</strong><span>Scout’s observations</span></div></div><div className={'memory-status '+(data.profileMemory?.status==='synced'?'synced':'')}><span className="live-dot"/>{data.profileSyncing?'Syncing to Scout…':data.profileMemory?.status==='synced'?`Synced ${new Date(data.profileMemory.syncedAt).toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit'})}`:data.profileMemory?.status==='error'?'Sync needs a retry':'Ready to sync'}</div><button type="button" className="button full outline" disabled={reading||!data.profileMemory?.syncedAt} onClick={read}>{reading?<LoaderCircle className="spin" size={14}/>:<FileText size={14}/>}Open notebook<ChevronRight size={14}/></button><button type="button" className="memory-sync" disabled={locked} onClick={sync}><RefreshCw size={12}/>Sync to Scout</button></aside><BotAccess/></div></div>
 {notebook&&<div className="concierge-overlay" onClick={e=>e.target===e.currentTarget&&setNotebook(null)}><div className="notebook-modal"><button className="setup-close icon-button" aria-label="Close notebook" onClick={()=>setNotebook(null)}><X size={20}/></button><h2>Scout’s notebook</h2><div className="notebook-tabs">{[['profile','PROFILE.md'],['notes','NOTES.md']].map(([id,title])=><button key={id} className={file===id?'active':''} onClick={()=>setFile(id)}>{title}</button>)}</div><pre>{notebook[file]||'This file has not been created yet.'}</pre><small>Read from your Agent37 computer</small></div></div>}
 </section>
}
function SparkleIcon(){return <Palette size={18}/>}
