import React,{useEffect,useRef,useState} from 'react';
import {Plus,Repeat2,Check,X} from 'lucide-react';
export const repeatNames={daily:'Daily',weekdays:'Weekdays',weekly:'Weekly',monthly:'Monthly'};
export function repeatLabel(schedule){return schedule?`${repeatNames[schedule.frequency]} · ${schedule.time}`:'One time'};
export default function SchedulePicker({value,onChange}){
 const [open,setOpen]=useState(false),root=useRef(null);
 useEffect(()=>{if(!open)return;const outside=e=>{if(!root.current?.contains(e.target))setOpen(false)};const key=e=>{if(e.key==='Escape')setOpen(false)};document.addEventListener('pointerdown',outside);document.addEventListener('keydown',key);return()=>{document.removeEventListener('pointerdown',outside);document.removeEventListener('keydown',key)}},[open]);
 const choose=frequency=>onChange(frequency==='once'?null:{frequency,time:value?.time||'08:00',dayOfWeek:value?.dayOfWeek??1,dayOfMonth:value?.dayOfMonth??1});
 return <div className="schedule-picker" ref={root}><button type="button" className={'schedule-trigger '+(value?'has-repeat':'')} aria-label="Task schedule" aria-expanded={open} onClick={()=>setOpen(!open)}>{value?<Repeat2 size={15}/>:<Plus size={15}/>}</button>{value&&<span className="schedule-selected">{repeatNames[value.frequency]}</span>}{open&&<div className="schedule-popover" role="dialog" aria-label="Task schedule"><div className="schedule-heading"><strong>Repeat task</strong><button type="button" aria-label="Close schedule" onClick={()=>setOpen(false)}><X size={13}/></button></div><div className="schedule-options">{[['once','One time'],...Object.entries(repeatNames)].map(([id,label])=><button type="button" key={id} aria-pressed={(value?.frequency||'once')===id} onClick={()=>choose(id)}>{label}{(value?.frequency||'once')===id&&<Check size={13}/>}</button>)}</div>{value&&<div className="schedule-settings">{value.frequency==='weekly'&&<label>On<select aria-label="Day of week" value={value.dayOfWeek} onChange={e=>onChange({...value,dayOfWeek:Number(e.target.value)})}>{['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'].map((name,i)=><option value={i} key={name}>{name}</option>)}</select></label>}{value.frequency==='monthly'&&<label>Day<select aria-label="Day of month" value={value.dayOfMonth} onChange={e=>onChange({...value,dayOfMonth:Number(e.target.value)})}>{Array.from({length:31},(_,i)=><option value={i+1} key={i}>{i+1}</option>)}</select></label>}<label>At<input aria-label="Repeat time" type="time" value={value.time} onChange={e=>onChange({...value,time:e.target.value})}/></label><small>First run now. Repeats in Pacific time.</small></div>}<button className="schedule-apply" type="button" onClick={()=>setOpen(false)}>Apply</button></div>}</div>
}
