import React,{useState} from 'react';
import {ArrowUp,Check,Pause,Play,RotateCcw,Plus,ChevronDown,ExternalLink,X,MapPin,Clock,ArrowRight,Globe} from 'lucide-react';
import {taskSections,taskStage,taskOutcome,completionTime,completedTaskCard} from './task-presentation';
import './tasks.css';
import SchedulePicker,{repeatLabel} from './SchedulePicker';
function Task({task,onAnswer,onRetry,onDismiss,onFindAnother,context}){
 const [answer,setAnswer]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[expanded,setExpanded]=useState(false);
 const completed=task.status==='completed',card=completed?completedTaskCard(task):null;
 async function submit(e){e.preventDefault();if(!answer.trim())return;setBusy(true);try{await onAnswer(task.id,answer);setAnswer('')}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <li className={'task-row task-'+task.status+(completed&&!card.matched?' no-match':'')}>
 <div className="task-line"><span className={'task-check '+(completed?'is-complete':'')} role="img" aria-label={completed?'Completed task':'Incomplete task'}>{completed&&<Check size={12} strokeWidth={3}/>}</span><button className="task-title" onClick={()=>setExpanded(!expanded)} aria-expanded={expanded}><span>{completed?card.headline:task.text}</span>{completed&&<small>{card.subheading}</small>}{task.recurrence&&<small className="task-repeat-label">{repeatLabel(task.recurrence)}{!task.recurrence.enabled?' · Paused':''}</small>}</button><div className="task-meta">{!completed&&<span className={'task-status status-'+task.status}>{taskStage(task,context)}</span>}{completed&&task.finishedAt&&<time dateTime={task.finishedAt}>{completionTime(task.finishedAt)}</time>}{completed&&<button className="task-dismiss" aria-label={'Dismiss '+task.text} title="Dismiss task" onClick={()=>onDismiss([task.id])}><X size={14}/></button>}{['failed','paused'].includes(task.status)&&<button className="task-retry" aria-label={'Retry '+task.text} onClick={()=>onRetry(task.id)}><RotateCcw size={13}/></button>}</div></div>
 {completed&&<div className="task-outcome"><div className="task-facts">{task.coverage?.providers?.length>0&&<span title={task.coverage.providers.map(p=>p.name).join(", ")}><Globe size={12}/>{task.coverage.providers.length} {task.coverage.providers.length===1?"source":"sources"} explored{!card.matched&&task.coverage.limited?" · limited search":""}</span>}{card.matched&&<span className="task-free">$0</span>}{card.when&&<span><Clock size={12}/>{card.when}</span>}{card.where&&<span><MapPin size={12}/>{card.where}</span>}{card.offer?.benefits?.slice(1,3).map((b,i)=><span key={i}><Check size={11}/>{b.label}</span>)}</div><div className="task-next"><div><ArrowRight size={11}/><strong>{card.next}</strong></div>{card.href?<a href={card.href} target="_blank" rel="noreferrer">{card.action}<ArrowRight size={13}/></a>:<button onClick={()=>onFindAnother(task)}>{card.action}<ArrowRight size={13}/></button>}<button className="task-detail-toggle" onClick={()=>setExpanded(!expanded)}>{expanded?'Less':'Details'}</button></div></div>}
 {task.status==='needs_input'&&task.question&&<form className="task-question" onSubmit={submit}><p>{task.question.prompt}</p>{task.question.choices?.length>0&&<div className="task-choices">{task.question.choices.map(choice=><button type="button" key={choice} aria-pressed={answer===choice} onClick={()=>setAnswer(choice)}>{choice}</button>)}</div>}<div className="task-answer"><input aria-label="Your answer" placeholder="Or write your answer…" value={answer} onChange={e=>setAnswer(e.target.value)} disabled={busy}/><button aria-label="Send answer" disabled={busy||!answer.trim()}><ArrowUp size={16}/></button></div>{error&&<small role="alert">{error}</small>}</form>}
 {expanded&&<div className="task-detail"><p className="task-original-request">{task.text}</p><p>{task.result||''}</p>{task.coverage?.providers?.length>0&&<div className="coverage-sources">{task.coverage.providers.map(p=><span key={p.domain}>{p.name}<small>{p.opened?"Page requested":"Searched"}{p.freeMatches?" · free option":""}</small></span>)}</div>}{(task.opportunities||[]).map(o=><a key={o.id||o.url} href={o.url} target="_blank" rel="noreferrer">{o.title}<ExternalLink size={12}/></a>)}</div>}
 {task.error&&<p className="task-error">{task.error}</p>}
 </li>
}
export default function TaskList({tasks=[],paused,onAdd,onAnswer,onRetry,onPause,onDismiss,onScheduleChange,mission,discovery}){
 const [text,setText]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[showAll,setShowAll]=useState(false),[undo,setUndo]=useState(null),[schedule,setSchedule]=useState(null);
 async function dismiss(ids){try{await onDismiss(ids,true);setUndo(ids);setError('')}catch(e){setError(e.message)}}
 async function restore(){try{await onDismiss(undo,false);setUndo(null);setError('')}catch(e){setError(e.message)}}
 async function submit(e){e.preventDefault();if(!text.trim())return;setBusy(true);setError('');try{await onAdd(text,schedule);setText('');setSchedule(null)}catch(e){setError(e.message)}finally{setBusy(false)}}
 const {open,completed,completedToday}=taskSections(tasks),context={mission,discovery,paused};
 async function findAnother(task){try{await onAdd(('Search more broadly using the source map for this request: '+task.text+' Previous answers: '+(task.answers||[]).map(a=>a.answer).join('; ')+'. Check independent alternatives, not only the preferred provider.').slice(0,1200));setError('')}catch(e){setError(e.message)}}
 const row=t=><Task key={t.id} task={t} onAnswer={onAnswer} onRetry={onRetry} onDismiss={dismiss} onFindAnother={findAnother} context={context}/>;
 return <section className="scout-tasks" aria-label="Scout tasks"><div className="tasks-heading"><h2>Tasks</h2><div><span className="tasks-today"><Check size={12}/>{completedToday} completed today</span>{open.length>0&&<button className="task-pause" onClick={()=>onPause(!paused)}>{paused?<Play size={12}/>:<Pause size={12}/>} {paused?'Resume queue':'Pause queue'}</button>}</div></div>
 <form className="task-composer" onSubmit={submit} aria-busy={busy}><SchedulePicker value={schedule} onChange={setSchedule}/><input aria-label="Give Scout a task" maxLength={1200} placeholder="Add a task for Scout…" value={text} onChange={e=>setText(e.target.value)} disabled={busy}/><button aria-label="Add task" disabled={busy||text.trim().length<3}><ArrowUp size={16}/></button></form>{error&&<p className="task-error" role="alert">{error}</p>}
 {tasks.some(t=>t.schedule)&&<details className="task-schedules"><summary>{tasks.filter(t=>t.schedule?.enabled).length} repeating tasks</summary>{tasks.filter(t=>t.schedule).map(t=><div key={t.id}><span>{t.text}<small>{repeatLabel(t.schedule)}{!t.schedule.enabled?' · Paused':''}</small></span><button onClick={()=>onScheduleChange(t.id,!t.schedule.enabled)}>{t.schedule.enabled?'Pause repeat':'Resume repeat'}</button></div>)}</details>}
 <div className="task-section-label"><h3>To do</h3><span>{open.length}</span></div>{open.length?<ul className="task-list" aria-label="To do">{open.map(row)}</ul>:<p className="tasks-clear">All caught up. Nothing waiting.</p>}
 {completed.length>0&&<><div className="task-section-label recent"><h3>Recently completed</h3><button className="clear-recent" onClick={()=>dismiss(completed.map(t=>t.id))}>Clear recent</button></div><ul className="task-list completed-task-cards" aria-label="Recently completed">{(showAll?completed:completed.slice(0,5)).map(row)}</ul>{completed.length>5&&<button className="task-history" onClick={()=>setShowAll(!showAll)}>{showAll?'Show recent only':`Show all ${completed.length} completed tasks`}<ChevronDown size={12}/></button>}</>}
 {undo&&<div className="task-undo" role="status">{undo.length===1?'Task dismissed':'Recent tasks cleared'}<button onClick={restore}>Undo</button></div>}
 </section>
}
